services:
  server:
    build:
      context: .
    volumes:
      - .:/app
    command: uvicorn blog.main:app --reload --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  postgres_data:
