"""Added cover_img in blogs

Revision ID: 2c669db606e5
Revises: c986168cd54e
Create Date: 2021-07-08 15:06:15.230262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c669db606e5'
down_revision = 'c986168cd54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
