"""init migration

Revision ID: 405d188187a2
Revises: 
Create Date: 2021-05-24 14:14:30.274020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405d188187a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_identifier', sa.String(), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('email', sa.String(), nullable=True),
                    sa.Column('role', sa.String(), nullable=True),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('blogs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('body', sa.String(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_blogs_id'), 'blogs', ['id'], unique=False)

    from sqlalchemy.orm import Session
    from user.helpers.hashing import pwd_cxt

    # # #################
    bind = op.get_bind()
    session = Session(bind=bind)
    hs_password = pwd_cxt.hash('sysadmin')
    insert_sysadmin_sql = "INSERT INTO USERS (NAME,EMAIL,ROLE,USERNAME,PASSWORD,CREATED_AT,IS_CONFIRMED,IS_ACTIVE) VALUES ('sysadmin','sysadmin@mail.com', 'sysadmin','sysadmin','{var_password}',NOW(), true, true)"
    session.execute(insert_sysadmin_sql.format(var_password=hs_password))
    # # #################
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_id'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
