"""Added created_at column in blog table

Revision ID: 5351225d70fd
Revises: 5dfc180cc7b3
Create Date: 2021-07-03 16:03:18.030751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5351225d70fd'
down_revision = '5dfc180cc7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'created_at')
    # ### end Alembic commands ###
