"""refactor blog table

Revision ID: a00fea09362f
Revises: 
Create Date: 2021-09-22 16:11:27.093575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00fea09362f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'cover_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('cover_image', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
