"""Added user_identifier(uuid)

Revision ID: da979ddb778f
Revises: 623c06223e56
Create Date: 2021-05-23 17:40:34.071635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da979ddb778f'
down_revision = '623c06223e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column(
        'user_identifier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_confirmed',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    op.drop_column('users', 'user_identifier')
    # ### end Alembic commands ###
